name: Test

on: [pull_request]

jobs:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Run envsubst
        uses: ./
        with:
          input: ./test/template
          output: ./test/output
        env:
          NAME: world
      - name: Print output
        run: cat ./test/output
      - name: Test
        run: '[[ "$(cat ./test/output)" = "Hello, world" ]]'
